apiVersion: v1
kind: Service
metadata:
  name: toannv15-devops-capstone
spec:
  selector:
    app: toannv15-devops-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer